### ISSUE TITLE
Replace Listener calls with 'call'

### ISSUE THREAD

**Issue by sureshjoshi** [RobotPajamas/Blueteeth#10]
Just for consistency, instead of having `OnCharacteristicWriteListener.onCharacteristicWritten`, replace that with `OnCharacteristicWriteListener.call` across the board. On one hand, it's less specific - but on the flipside, the listener name makes it clear what's actually happening, so the `onCharacteristicWritten` is redundant.

Also, my personal ideal is to use lambdas everywhere (and since the libraries are already there internally, it's exposed externally), the `onCharacteristicWritten` disappears anyways.

**Comment by martiwi** [comment]
Hello @sureshjoshi ,

It's a pleasure to see finally someone who had time to build a BLE library ;)
I've worked now since a few years with BLE devices on Android gaining me some experiences I would like to share on this project.

But first, I would like to ask you a few questions about your choice.
1- As it is a direct response to a command, why calling this class Listeners, as it is Callbacks. Listeners for me would be the one your would like to register for a specific characteristic changes for example, which is missing from now on the library.
2- Is there iany good reason why there is no Error callbacks on each of yours current Listeners. As Connection may fail (and god, this a happenning to often : Error:133 on connection is a good example =) )
3- As it is not possible to do anything on the remote BLE device without having discovering the services, I would suggest to postpone the connection status after having discovering them.

**Comment by sureshjoshi** [comment]
Hey @martiwi, I'd love any help you can provide! 

1 - Registering for notifications/indications is an enhancement in issue #5. 

I'm using the 'Listener' terminology to stay consistent with a lot of my other projects. I agree Callbacks might be another name (they used to be called callbacks, I re-named them recently). I think it's just semantics, and I prefer Listener (e.g. I'm listening for a connection event, listening for a write event, etc...).

2 -  Errors are not -currently- there, true. They're not never going to be there  :) I have issue #9 open for that purpose where I want to remove all boolean returns, and add my error handling (via enums). E.G. Response.NO_ERROR, Response.BUSY, etc...

The reason for all async is mentioned in that issue. Essentially, it makes it forward compatible with the upcoming 'queue-based' calls, and everything is already async, as I'm putting it on the UI thread... So, I should be checking error conditions at call time, not post time.

3 - This is a good point, I was debating this myself for a while - don't have an answer. Recently, I was using a BLE SDK on another project, and they delay connection callbacks until after services and characteristics have been discovered. I find it to be very error prone and it can take 10-20 seconds just for a connection. From an end-user usability point of view, I think the option to handle things lazily, and exposing that ability to the developer is critical (rather than completely hiding away those abilities from the dev).  <-- Read: I absolutely hated this 'feature' of theirs.

My BluetoothUtils class, on the other hand, makes use of what you've suggested. It always ensures we call discoverServices before trying to write something. So, a developer could use that inside of their class across the board. 

It's a hard balance to make everything 'safe' and trying to not hinder more advanced developers. I just look at it as though I was a consumer, not a writer, and what I would hate the library creator for adding/not adding.   :)

I was going to put some time into it this week to start knocking off issues, and hopefully release 0.2.0 by next weekend. It should be a bit more feature rich and cleaner to work with by then (the pairing/bonding needs a lot of work - it's only at an infancy level of completion, but at the same time, I haven't seen too many libraries which include pairing code anyways... Specifically, error handling and retries).

**Comment by martiwi** [comment]
@sureshjoshi Sounds good :) Agree on most points.

> The reason for all async is mentioned in that issue. Essentially, it makes it forward compatible with the upcoming 'queue-based' calls, and everything is already async, as I'm putting it on the UI thread... So, I should be checking error conditions at call time, not post time.

About that, in fact you're right to point Samsung out cos of their bug for handling connection in the main thread... but from my last test it was fixed since Lollipop release. At least on a Samsung S4 it's working out of the main thread, same for S6 running on Marshmallow. So it can be run in a dedicated thread. Better performance during connection and BLE operation, and avoid to freeze the UI.
`
if (Build.MANUFACTURER.equalsIgnoreCase("samsung") && Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            // Connect in the main thread
            } else {
                // Connect in a dedicated thread
            }`
Not that pretty, but better perf.

**Comment by sureshjoshi** [comment]
Hey @martiwi, good point - however, going the route of exclusions per manufacturer and device version might get risky and very busy. At least until Android 4.4 really goes away (e.g. when Android 7/8 comes out). They're not the only manufacturer with 4.4 issues.

Samsung is the most notorious one for these problems, but right now, I'm working on a project where we test about 15-20 different devices with different operating systems, with BLE - and I'll say that device-specific problems come up quite often. 

At the moment, initiating a call from the main thread (or from a dedicated service?) seems to be the 'cleanest' resolution for all of them (as much as I can make a blanket statement). I would like to get to the point where a user passes in a thread, or a handler, and everything just works. Right now, I'm wondering if something on the same lines as Robospice might work (as in, create a Robospice binding to handle the threading and lifecycle issues, decoupling this library from manufacturer problems).
